version: '3.1'

services:
  ordering_service:
    image: 'adoptopenjdk/maven-openjdk11'
    build:
      context: .
    container_name: ordering_service
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Pass1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresql:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass1234